"""
CLI Entry Point for Multi-LLM Review.

Usage:
    python -m features.multi_llm_review.cli run --commit <sha>
    python -m features.multi_llm_review.cli pr-comment --commit <sha> --pr-number <num>
"""

import argparse
import sys
from pathlib import Path
from typing import Optional

from features.multi_llm_review.orchestrator.orchestrator import (
    OrchestratorConfig,
    ReviewOrchestrator,
)
from features.multi_llm_review.review_schemas import ReviewTask
from runtime.database import get_connection
from runtime.event_store import EventStore


def create_event_store() -> EventStore:
    """Create EventStore instance."""
    conn = get_connection()
    return EventStore(conn)


def run_review(
    commit: str,
    review_type: str = "full",
    files: Optional[list[str]] = None,
) -> int:
    """Run review for a commit."""
    orchestrator = ReviewOrchestrator(
        event_store=create_event_store(),
        config=OrchestratorConfig(),
    )

    task = ReviewTask(
        target_commit=commit,
        review_type=review_type,
        target_files=files or [],
    )

    result = orchestrator.run_review(task)

    print(f"Review completed: {result.run_id}")
    print(f"Status: {result.consensus.status}")
    print(f"Confidence: {result.consensus.confidence:.2f}")
    print(f"Duration: {result.duration_seconds:.1f}s")
    print(f"Findings: {sum(len(f) for f in result.agent_findings.values())}")
    tv = result.technical_verification
    print(f"Technical Verification: {'PASS' if tv.tests_passed else 'FAIL'}")

    if result.errors:
        print(f"Errors: {result.errors}")

    # Write status for CI
    Path("/tmp/evidence-run/status.txt").write_text(result.consensus.status)

    return 0 if result.consensus.status in ("VERIFIED", "PARTIALLY") else 1


def pr_comment(
    commit: str,
    pr_number: int,
    output: str,
) -> int:
    """Generate PR comment from review evidence."""
    from runtime.database import get_connection
    from runtime.event_store import EventStore

    conn = get_connection()
    store = EventStore(conn)

    # Query review results for this commit
    events = store.replay(topic="review.consensus")
    consensus = None
    for event in events:
        if event.payload.get("review_task_id") == commit:
            from features.multi_llm_review.review_schemas import Consensus
            consensus = Consensus(**event.payload)
            break

    if not consensus:
        return 1

    # Query findings
    finding_events = store.replay(topic="review.finding")
    findings_by_role = {}
    for event in finding_events:
        if event.payload.get("review_task_id") == commit:
            role = "unknown"
            # Determine role from finding or context
            findings_by_role.setdefault(role, []).append(event.payload)

    # Generate markdown
    md = [
        "## 🔍 Multi-LLM Review Results",
        "",
        f"**Commit:** `{commit[:8]}`",
        f"**Status:** {consensus.status}",
        f"**Confidence:** {consensus.confidence:.1%}",
        "",
        "### Technical Verification",
        f"- Tests: {'✅ PASS' if consensus.technical_verification.tests_passed else '❌ FAIL'}",
        f"- Coverage: {consensus.technical_verification.coverage_pct:.1f}%",
        "",
    ]

    if consensus.dissent:
        md.append("### ⚠️ Dissent")
        for d in consensus.dissent:
            md.append(f"- {d}")
        md.append("")

    if consensus.recommended_actions:
        md.append("### 📋 Recommended Actions")
        for action in consensus.recommended_actions:
            md.append(f"- {action}")
        md.append("")

    md.append("---")
    md.append("*Generated by MUSCAL Multi-LLM Review*")

    Path(output).write_text("\n".join(md))
    return 0


def main():
    parser = argparse.ArgumentParser(description="MUSCAL Multi-LLM Review CLI")
    subparsers = parser.add_subparsers(dest="command", required=True)

    # Run command
    run_parser = subparsers.add_parser("run", help="Run review for a commit")
    run_parser.add_argument("--commit", required=True, help="Target commit SHA")
    run_parser.add_argument(
        "--type",
        default="full",
        choices=["full", "security", "architecture", "quality", "pr"],
    )
    run_parser.add_argument("--files", nargs="*", help="Specific files to review")

    # PR Comment command
    comment_parser = subparsers.add_parser("pr-comment", help="Generate PR comment from review")
    comment_parser.add_argument("--commit", required=True, help="Target commit SHA")
    comment_parser.add_argument("--pr-number", type=int, required=True, help="PR number")
    comment_parser.add_argument("--output", required=True, help="Output file path")

    args = parser.parse_args()

    if args.command == "run":
        sys.exit(run_review(args.commit, args.type, args.files))
    elif args.command == "pr-comment":
        sys.exit(pr_comment(args.commit, args.pr_number, args.output))
